### ISSUE TITLE
Images not showing in PDF?

### ISSUE THREAD

**Issue by gbarnabic** [travs/markdown-pdf#100]
Is this a missing feature or am I somehow doing it wrong?  I do see the image in the preview shift-ctrl-M so the syntax is correct.

Anyway it would be nice to be able to have them in the output.

**Comment by travs** [comment]
This should be working now. Where are the images stored? Reopen and add detail if it persists.

**Comment by holzkohlengrill** [comment]
I still have this error. Any suggestion?

**Comment by shark-oxi** [comment]
Still having the bug for pictures (relative link) in the same folder.

**Comment by cmacdonnacha** [comment]
Same issue for me when using relative links:
`assets/images/my-image.png`

Absolute paths work fine:
`https://www.w3schools.com/howto/img_fjords.jpg`

**Comment by travs** [comment]
Going to try to make this more robust if possible. If this is failing for you, what OS are you on, atom version, etc.

**Comment by travs** [comment]
Going to try to make this more robust if possible. If this is failing for you, what OS are you on, atom version, etc.

@cmacdonnacha

**Comment by MaxWinsemius** [comment]
I got a similar error, but it only occurs if I add `=300x` behind the link (which works with normal MD).

```
$ apm -v
apm  2.1.1
npm  6.4.1
node 10.10.0 x64
atom 1.30.0
python 2.7.15
git 2.19.0

OS: Arch linux x86_64, Kernel 4.18.6
```

**Comment by sl0burn** [comment]
On windows 7 64bit.
Have image link like this ![logo](/Images/logo-big.png "logo")
Is not displaying in PDF.

**Comment by martimlobao** [comment]
This doesn't work:
```# ![logo](/assets/logo-small.png)```
but this does:
```# ![logo](assets/logo-small.png)```

```
$ apm -v
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 3.6.6
git 2.21.0

OS: macOS 10.14.3 (Mojave)
```

**Comment by danbz** [comment]
had the same issue on OSx 10.13.6
I changed image paths from

``` ![image example](/images/example.jpg) ```

to path with leading dot and voila....

``` ![image example](./images/example.jpg)```

github markdown is happy either way and now i can render pdfs with correct images i.

**Comment by travs** [comment]
Going to close this and add something to the README
