### ISSUE TITLE
Tables don't work

### ISSUE THREAD

**Issue by jajaperson** [travs/markdown-pdf#174]
Converting markdown documents with tables just results in |s and :---------s showing up

| I'm sad
| :------
| Please add tables

**Comment by centell** [comment]
I met same problem. :-: is not working but --- is working.

**Comment by travs** [comment]
Late reply: this should work now, since we use mdpdf to do the conversion

**Comment by alaut** [comment]
:-: still doesn't seem to work for me but --- does

**Comment by dret** [comment]
yup, tables indeed still do not work. maybe reopen the issue?

**Comment by travs** [comment]
This is being tracked over here: https://github.com/showdownjs/showdown/issues/778
